package models;
// Generated 10 oct 2021 12:50:13 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer id;
     private String firstName;
     private String lastName;
     private String email;
     private Date lastLogin;
     private Boolean isActive;
     private Date dateJoined;
     private String password;
     private String username;
     private Boolean isSuper;

    public User() {
    }

    public User(String firstName, String lastName, String email, Date lastLogin, Boolean isActive, Date dateJoined, String password, String username, Boolean isSuper) {
       this.firstName = firstName;
       this.lastName = lastName;
       this.email = email;
       this.lastLogin = lastLogin;
       this.isActive = isActive;
       this.dateJoined = dateJoined;
       this.password = password;
       this.username = username;
       this.isSuper = isSuper;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Date getLastLogin() {
        return this.lastLogin;
    }
    
    public void setLastLogin(Date lastLogin) {
        this.lastLogin = lastLogin;
    }
    public Boolean getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }
    public Date getDateJoined() {
        return this.dateJoined;
    }
    
    public void setDateJoined(Date dateJoined) {
        this.dateJoined = dateJoined;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public Boolean getIsSuper() {
        return this.isSuper;
    }
    
    public void setIsSuper(Boolean isSuper) {
        this.isSuper = isSuper;
    }




}


